title: XI
description: World Space / VR UI Framework for Unity
theme: just-the-docs

url: https://LacombeJ.github.io/xi-docs-site
logo: "/assets/tobia-logo.png"
favicon_ico: "/assets/tobia-logo.png"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red